"""Constants for SMARTFOX."""
DOMAIN = "smartfox"
CONF_UNIT_ID = "unit_id"
DEFAULT_PORT = 502
DEFAULT_UNIT_ID = 1
DEFAULT_SCAN_INTERVAL = 30
MANUFACTURER = "DAfi / SMARTFOX"
MODEL = "SMARTFOX Pro / Pro 2"
